#pragma once

enum {
  WORKER_KEY_ECZEMAMALOGGER_START,
  WORKER_KEY_ECZEMAMALOGGER_STOP,
  WORKER_KEY_ECZEMAMALOGGER_TOGGLE,
  WORKER_KEY_ECZEMAMALOGGER_RESET,
  WORKER_KEY_ECZEMAMALOGGER_UPDATE,
};

enum {
  PERSIST_KEY_IS_LOGGING = 100,
};
